// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARRz0cMEOe3RTMZPQbq1rUWhyp69Wp3xk',
    appId: '1:753482130358:web:31bd4dd8bfd76098871717',
    messagingSenderId: '753482130358',
    projectId: 'yilink-health',
    authDomain: 'yilink-health.firebaseapp.com',
    storageBucket: 'yilink-health.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnqnioPiLEWEdWzYWYblufru1ahVAcKho',
    appId: '1:753482130358:android:edea9baa4b42050c871717',
    messagingSenderId: '753482130358',
    projectId: 'yilink-health',
    storageBucket: 'yilink-health.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj5eZ62-_0--JoK0P4N7Qb3gKGUxMpTHA',
    appId: '1:753482130358:ios:d14432f8082728fa871717',
    messagingSenderId: '753482130358',
    projectId: 'yilink-health',
    storageBucket: 'yilink-health.firebasestorage.app',
    iosClientId: '753482130358-cbqbnp6t7u9r8t993h5j2gtsjbdh7rsa.apps.googleusercontent.com',
    iosBundleId: 'com.example.yilinkHealthMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj5eZ62-_0--JoK0P4N7Qb3gKGUxMpTHA',
    appId: '1:753482130358:ios:d14432f8082728fa871717',
    messagingSenderId: '753482130358',
    projectId: 'yilink-health',
    storageBucket: 'yilink-health.firebasestorage.app',
    iosClientId: '753482130358-cbqbnp6t7u9r8t993h5j2gtsjbdh7rsa.apps.googleusercontent.com',
    iosBundleId: 'com.example.yilinkHealthMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARRz0cMEOe3RTMZPQbq1rUWhyp69Wp3xk',
    appId: '1:753482130358:web:e21c53b51b75fdc0871717',
    messagingSenderId: '753482130358',
    projectId: 'yilink-health',
    authDomain: 'yilink-health.firebaseapp.com',
    storageBucket: 'yilink-health.firebasestorage.app',
  );
}
